version: "3.9"

services:
  local-db:
    image: mysql:8.0.28-oracle
    container_name: rnkm-local-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rnkm-db
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "5432:5432"

  local-cache:
    image: bitnami/redis:6.2.6
    container_name: rnkm-cache
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
