package seed

import (
	"github.com/isd-sgcu/rnkm65-backend/src/app/model/baan"
	constant "github.com/isd-sgcu/rnkm65-backend/src/constant/baan"
)

var baans = []baan.Baan{
	{
		NameTH:        "บ้านนางงาม",
		DescriptionTH: "บ้านรับน้องผู้เปิดประตูตำนานบทใหม่ แห่งจุฬาลงกรณ์มหาวิทยาลัย \nSince 2022\nรับน้องก้าวใหม่ 65 สวยงามพร้อมกันทั้งจุฬา แบบใหม่แบบสับ \nเปิดประตูสู่นางงามของเรา ใครมันจะมาต้าน!!!\nมาร่วมกันเปิดตำนาน ที่บ้านนางงามสิคะ",
		NameEN:        "B✨ng",
		DescriptionEN: "The house for the youngest who opened the door for a new chapter of the legend. of Chulalongkorn University\nSince 2022\n Accepting new young steps, 65, beautiful at the same time, Chulalongkorn University new hack\n Open the door to our beauty queen Who will come against!!!\nLet's join the legend At the beauty queen's house",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Lady-First.jpeg",
		Size:          constant.M,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "Baannangngam",
		InstagramUrl:  "https://www.instagram.com/baannangngam.official/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านคุณหนู",
		DescriptionTH: "บ้าน size s ที่แสนอบอุ่น เน้นทำกิจกรรม ไม่เน้นเต้นสัน และมีการเล่นบอร์ดเกมสร้างความสัมพันธ์ภายในบ้าน",
		NameEN:        "Baan Khun Noo",
		DescriptionEN: "A small warm house focused on activities and bonding through tabletop and other games oriented activities over dancing.",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Khun-noo.png",
		Size:          constant.S,
		Facebook:      "BaanKhunNooCU",
		FacebookUrl:   "https://www.facebook.com/BaanKhunNooCU/",
		Instagram:     "baankhunnoo_official",
		InstagramUrl:  "https://www.instagram.com/baankhunnoo_official/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านโจ๊ะเด๊ะ ฮือซา",
		DescriptionTH: "ขนาดไก่ยังมีเล้า แล้วเธอเล่าไม่อยากมีเราบ้างหรอจ้ะ\n\n“บ้านโจ๊ะเด๊ะ ฮือซา” พร้อมที่จะส่งต่อความสนุกให้ทุกๆคนแล้ววว \n\nไม่ว่าจะเป็นใคร มาจากที่ไหน คณะอะไร ก็สามารถมาจอยกันให้เต็มที่ ที่ ’บ้านโจ๊ะเด๊ะ’ \nบ้านที่มาพร้อมกับกิจกรรมที่น่าตื่นเต้น ท้าทาย และเกมสนุกๆ ที่กำลังรอทุกคนอยู่\n\nถึงเวลาแล้วที่ทุกคนรอคอย บ้านโจ๊ะเด๊ะหลังนี้ พร้อมที่จะเสิร์ฟความสนุกให้ทุกคนแล้ว!!! 4-6สิงหาคมนี้ มาเจอกั๊นน",
		NameEN:        "Baan Jodeh",
		DescriptionEN: "You all are invited !\n“Jodeh Huesa “ is readyyyy !\nno matter who you are, where you’re from, just enjoy!\n\nAugust 4-6 \nCan’t wait to see youuu",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Jodeh_icon.jpg",
		Size:          constant.M,
		Facebook:      "Jodeh Huesa",
		FacebookUrl:   "https://www.facebook.com/jodehcu/",
		Instagram:     "jodeh_official",
		InstagramUrl:  "https://www.instagram.com/jodeh_official/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านโจ๋",
		DescriptionTH: "ขึ้นชื่อว่าบ้านโจ๋ จะไม่โก๋ได้ยังไงงงงง\n\nต้อนรับฤดูกาลแห่งการรับเพื่อนประจำปี พ.ศ. 2565 มาด้วยความสยองสุดเร้าใจไปกับธีม the conjo+ringที่จะรวบรวมความสนุก+สยองหลากหลายรูปแบบเข้าไว้ด้วยกัน และรวมถึงกิจกรรมที่บ้านโจ๋ขึ้นชื่อที่สุดนั่นก็คือ การสันทนาการ นั่นเองงงง\n\nเอ้ะๆแต่ว่า ความสนุกกับความสยองมันจะมามัดรวมกันได้ยังไง \nถ้าอยากรู้ ก็มาเจอกันได้ที่บ้านโจ๋นะค้าบบบบ\n\nมาร่วมเป็นส่วนหนึ่งของครอบครัวที่อบอุ่นของเรากันนะงับบ พวกเรา welcome ทุกคนเลยค่าาาา",
		NameEN:        "Baan Jo",
		DescriptionEN: "Baan Jo+ is coming back!                                                                    \n\nThe season of Friend Welcoming of year 2022 has come with dramatic scary atmosphere. In the theme of conjo+ring,  you will meet fun and frightening activities especially the surprisingly recreation which is the most famous of Baan Jo+.\n\nLike to know how's the fun & the horror could be blended together,  come & join our warm family @Baan Jo+.  See u all kaa!!",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Jo.png",
		Size:          constant.L,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanjochula",
		InstagramUrl:  "https://www.instagram.com/baanjochula",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านอะอึ๋ม",
		DescriptionTH: "คาสิโนก็เลยกลับมาเปิดทำการ\nหลังจากปิดตัวไปเนื่องด้วย สถานการณ์covid\n\nอะอึ๋มคาสิโน ขอเชิญน้องๆมาร่วมกิจกรรม ที่มาในตีมคาสิโน รับรองได้ว่าเข้าบ้านนี้ มีเเต่ความสนุกที่รอน้องๆอยู่",
		NameEN:        "Baan Aaum",
		DescriptionEN: "Aaum casino is back \n After closing due to covid situation\n Aaum Casino invites all of you to join our Baan Aaum which came with the casino theme.\nWe're all guaranteed that “Baan Aaum” full of fun activities waiting for you",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Aaum.jpeg",
		Size:          constant.M,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanaaum.official",
		InstagramUrl:  "https://instagram.com/baanaaum.official",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "Work",
		DescriptionTH: "ถ้านี่คืองานสุดท้ายแล้ว เราอยากจะทำอะไรมากที่สุด? \n“Work for the Road” คือบาร์ชื่อดังที่คอยเปิดต้อนรับเฟรชชี่ทุกท่าน พร้อมเสิร์ฟเครื่องดื่มอันเป็นเอกลักษณ์จากทางบ้านให้แต่ละคน ร่วมดื่มด่ำบรรยากาศสุดแสนล้ำค่าไปกับเรา ร่วมปลดปล่อยความเป็นตัวเองอย่างสนุกสุดเหวี่ยง และร่วมใช้เวลาทั้งหมดที่มีราวกับว่านี่คืองานสุดท้ายเพียงหนึ่งเดียว เพราะนี่คือ…”Work for the Road แก้วสุดท้าย…ก่อนบายเธอ” ",
		NameEN:        "Work",
		DescriptionEN: "What if this is the last event? What would you like to do the most?\n\"Work for the Road\" is a well-known bar, ready to welcome all freshmen. We will serve our exclusive drinks to you all. Join us and indulge in the most precious atmosphere. Unleash youself in a very amusing way. Spend all your time as if this is the only final event because this is...\"Work for the Road, one last drink...before goodbye\"",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Work.png",
		Size:          constant.S,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanwork.cu",
		InstagramUrl:  "https://instagram.com/baanwork.cu",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านว้อนท์",
		DescriptionTH: "บ้านแห่งภาพยนตร์ สถานที่ที่รวมเรื่องราวอันหลากหลายมาไว้ด้วยกัน ทั้งทุกข์ สุข เศร้า ดีใจ อารมณ์ต่าง ๆ ที่คนในบ้านหลังนี้ร่วมกันแบ่งปันและถ่ายทอดออกมาผ่านความรู้สึกต่าง ๆ ที่เกิดขึ้น สิ่งเหล่านี้จะช่วยให้ทุกคนที่ได้เข้ามาเติ่มอิ่มไปด้วยความประทับใจและอบอุ่น ถ้าคุณต้องการ CINEMA คุณต้องการ WANTED",
		NameEN:        "BAAN WANTED",
		DescriptionEN: "Haus of movies, a place that brings together stories of sorrow, sadness, joy and other emotions that people share and convey through their feelings. It will fill everyone's heart with a warm and touching feeling. If you want CINEMA, you want WANTED",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/BAAN-WANTED.jpg",
		Size:          constant.S,
		Facebook:      "BaanWanted",
		FacebookUrl:   "https://www.facebook.com/BaanWanted",
		Instagram:     "baan_wanted/",
		InstagramUrl:  "https://www.instagram.com/baan_wanted/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านโซ้ยตี๋หลีหมวย",
		DescriptionTH: "บ้านโซ้ยตี๋หลีหมวย\n\n“เตรียมตัวออกล่า แล้วไปจัดการ Vecna ด้วยกัน”\n\nพบกับบรรยากาศของบ้านที่เต็มไปด้วยความสนุกสนานอีกทั้งยังมีกลิ่นอายของยุค 80s อย่ามัวแต่รอคอย ถ้าอยากเอนจอยก็มาร่วมกับพวกเราชาวโซ้ยตี๋ได้เลย\nอย่าลืมเลือกบ้านโซ้ยตี๋นะ!",
		NameEN:        "Baan Soei Tee Lhee Mouy",
		DescriptionEN: "Come on freshy, the fancy adventure is waiting!\nBe prepared for the exciting 80s atmosphere. Don’t forget to come and join!\n\nInstagram : baansoeiteelheemouy\nFacebook : บ้านโซ้ยตี๋หลีหมวย SoeiteeLheemouy",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-soeiteelheemouy.jpg",
		Size:          constant.XL,
		Facebook:      "baansoeiteelheemouy",
		FacebookUrl:   "https://www.facebook.com/baansoeiteelheemouy",
		Instagram:     "baansoeiteelheemouy",
		InstagramUrl:  "https://www.instagram.com/baansoeiteelheemouy/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านสด",
		DescriptionTH: "Lockdown มาสองปี ปีนี้บ้านสดกลับมาแล้วพร้อมกับธีมสดใหม่\n\n\n\nตึ๊ง…ตึง…ตึ๊ง…ตึงงง ~\n\nประกาศจาก #นครสดมหาสนุก\nขอให้ชาว #SODTOPIA ทุกท่านเตรียมตั้งรับความสนุกอย่างสุด ๆ แบบสด ๆ ! \nที่กำลังจะเกิดขึ้นในนครแห่งนี้กันให้ดี ! \n\nบ้านสดยินดีต้อนรับ #CU106 ทุกคนเข้าสู่ #SODTOPIA #นครสดมหาสนุก ที่จะทำให้ความฝันของทุกคนเป็นจริง ไม่ว่าคุณจะมาจากคณะอะไร ไม่ว่าคุณจะมีความชอบแบบไหน \n#SODTOPIA พร้อมแล้วที่จะพาทุกคนไปพบปะเพื่อนใหม่ เอนจอยและปล่อยใจไปด้วยกัน\nแล้วมาสร้างมิตรภาพและความทรงจำในช่วงเวลาอันแสนพิเศษนี้ไปด้วยกันที่ #SODTOPIA \n\n แล้วพบกันวันที่ 4-6 สิงหาคมนี้ !",
		NameEN:        "Baan Sod",
		DescriptionEN: "After being in lockdown for the past two years, BaanSod has now returned with the newest theme “Sodtopia”.\n\n\n\nAttention please~\n\nBe prepared, our Sodtopians, an unprecedented entertainment experience is about to take place in this city!!!\n\nBaanSod is grateful to welcome #CU106 to #SODTOPIA, where your wishes and dreams will be fulfilled. Regardless of your faculties, we are ready to provide everyone with an opportunity to build friendships, meet numerous interesting people as well as participate in fun activities. Let’s seize the day and make precious memories together.\n\nSee u on 4-6 August!",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Sod.png",
		Size:          constant.XL,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baansod.official",
		InstagramUrl:  "https://www.instagram.com/baansod.official/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านอินดี้",
		DescriptionTH: "บ้าน INDY \n\nเปิดมานานกว่า 20 ปี ตอนนี้บ้านของเรากำลังจะเกิดเรื่องใหญ่ขึ้น มาร่วมเป็นสายลับและจัดการภารกิจให้สำเร็จ เกียมตัวเกียมจัยมาให้พร้อม แล้วมาพับกบ พบกับเรานะ WAKU❗️WAKU❗️",
		NameEN:        "Baan INDY",
		DescriptionEN: "INDY \nOur house has a long history.. But now, we’re facing big trouble! We need you all, THE RENOWNED SPY, to help us get through the mission together. prepare yourself and See you soon WAKU ❗️ WAKU ❗️",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Indy.jpg",
		Size:          constant.XL,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanindy.official",
		InstagramUrl:  "https://instagram.com/baanindy.official",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านอากาเป้",
		DescriptionTH: "บ้านอากาเป้เป็นครอบครัวขนาดเล็ก กำลังดี เป็นเซฟโซนที่สมาชิกทุกคนพร้อมมอบความรักและความห่วงใยให้กันและกัน ฉะนั้นแล้วความรักที่ไร้เงื่อนไขของเราเองจึงยากที่จะแตกสลาย\nมาเป็นส่วนหนึ่งของครอบครัวเรา แล้วมาสร้างความทรงจำดี ๆ ไปด้วยกันนะ! ( ´ ▽ ` )",
		NameEN:        "Baan Agape",
		DescriptionEN: "Baan Agape: \nThe warm family of just the right size. \nThe safe zone of everyone’s care.\nThe place of the unbreakable unconditional love. \nJoin us! Be a part of this memory… together ☺️",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Agape.png",
		Size:          constant.S,
		Facebook:      "Baan Agape Chula",
		FacebookUrl:   "https://www.facebook.com/baanagape",
		Instagram:     "baanagapechula",
		InstagramUrl:  "https://instagram.com/baanagapechula",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านคิดส์",
		DescriptionTH: "one way ticket back to the 90s please\nมาร่วมเดินทางย้อนวันวานไปกับบ้านคิดส์ ที่จะพาทุกคนกลับไปเป็น90s kidsกันในกิจกรรมรับเพื่อนก้าวใหม่ 2022 นอกจากจะได้สัมผัสบรรยากาศความสนุกแบบวัยรุ่น90 ยังได้รู้จักเพื่อนใหม่และได้ร่วมสร้างความทรงจำไปด้วยกัน",
		NameEN:        "Baan Kids",
		DescriptionEN: "one way ticket back to the 90s please\nWe gladly invite you to be a part of our time travel bringing everyone back to be 90s kids in Rubpeunkaomai 2022 Feels the 90’s vibe, makes new friends and seizes the beautiful memories together",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Kids.png",
		Size:          constant.L,
		Facebook:      "BaanKids",
		FacebookUrl:   "https://www.facebook.com/BaanKids",
		Instagram:     "baankids.official",
		InstagramUrl:  "https://www.instagram.com/baankids.official/",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านคุ้ม",
		DescriptionTH: "นะมัสเต … \nบ้านรับเพื่อนที่ได้กลับกลายเป็นตำนานที่เลือนหายไปหลังจากการแพร่ระบาดของโควิด-19 \nครั้งนี้ ! ในงานรับเพื่อนก้าวใหม่ 2565 บ้านคุ้มได้ลุกขึ้นมาทวงอำนาจอีกครั้ง\nจากการรอคอยอย่างเนิ่นนาน ในปีนี้บ้านคุ้มประกาศการกลับมาอย่างยิ่งใหญ่ด้วยธีม KOOMGUBAI ภาพยนตร์ที่เป็นกระแสโด่งดังในปี 2565 \nหลายคนอาจคิดว่าคงเป็น KOOMGUBAI แบบปกติ แต่เรารับรองว่าคุณจะคาดไม่ถึงกับสิ่งที่เราจะทำอย่างแน่นอน\nแล้วเจอกันในงานรับเพื่อนก้าวใหม่ 2565 ",
		NameEN:        "Baan Koom",
		DescriptionEN: "Namaste …  \nBaan Koom, The Legendary house, has faded after facing the COVID-19 pandemic. This time! Rubpuenkaomai 2022 , Baan Koom will rise to claim their power again.\nIn this year, Baan Koom announced a big comeback with the theme of KOOMGUBAI, inspired from the hit movie of 2022. \nMany people may think that it is so simple , but We assure you that you will see things that have never been seen in your life for sure. See you soon.",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-KOOM.png",
		Size:          constant.L,
		Facebook:      "บ้านคุ้ม",
		FacebookUrl:   "https://www.facebook.com/%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%B8%E0%B9%89%E0%B8%A1-127164760810245\n",
		Instagram:     "baankoom.chula",
		InstagramUrl:  "https://instagram.com/baankoom.chula",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านหรอย",
		DescriptionTH: "Accio Confundo นะโมนะโม เลิฟยูเลิฟยู\nอยากเป็นหรอย วีสลีย์ จะเสกให้พี่มารักแต่หนู~\n\n“เรียน คุณเฟรชแมน\n\nเรามีความยินดีที่จะแจ้งให้คุณทราบว่า โรงเรียนคาถาพ่อมดแม่มดและเวทมนตร์ศาสตร์จุฬาวอตส์รับคุณเข้าเรียนในปีนี้\n\nโรงเรียนเปิดวันที่ 4 สิงหาคม เราจะคอยนกฮูกของคุณจนถึงวันที่ 6 สิงหาคม\n\nขอแสดงความนับถือ”",
		NameEN:        "Baan Rhoy",
		DescriptionEN: "Accio Confundo Namo Namo Luv U Luv U~\n\n“Dear Mr/Miss Freshman,\n\nWe are pleased to in form you that you have a place at Chulawarts School of Witchcraft and Wizardry.\n\nTerm begins on 4 August. We await your owl by no later than 6 August.\n\nYour sincerely.”",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Rhoy-Weasley.png",
		Size:          constant.S,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanrhoy.chula",
		InstagramUrl:  "https://www.instagram.com/baanrhoy.chula",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านหลายใจ",
		DescriptionTH: "จงหยุด อยู่ตรงนั้น \nเจ้าพรหมลิขิตของฉัน \nส่งรักเธอให้ฉันมา อย่าให้ต้องเสียเวลา\nCupid อยู่ที่ไหน มาช่วยจับตัวเธอเอาไว้\nจะท่องคาถาในใจทันที…!\n\nยินดีต้อนรับสู่สำนักดูดวงบ้านหลายใจ สำนักของเราพร้อมฝึกฝนศิษย์หน้าใหม่ให้กลายเป็นแม่หมอพ่อมดสุดปังแห่งยุคสมัย \n\nถ้าอยากจะรู้ว่าชะตาชีวิตในสำนักบ้านหลายใจจะเป็นยังไง\n#แกก็ลองทายดูสิ \n\nFacebook: บ้านหลายใจ\nInstagram: baanlaijai\nTwitter  @baanlaijai",
		NameEN:        "Baan Lai Jai",
		DescriptionEN: "Welcome to Laijai horoscope! We’re now ready with the training for our member to become the coolest witches& wizards of the generation! \n\nFacebook: บ้านหลายใจ\nInstagram: baanlaijai\nTwitter  @baanlaijai",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-laijai.jpeg",
		Size:          constant.M,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanlaijai",
		InstagramUrl:  "https://instagram.com/baanlaijai",
		Line:          "",
		LineUrl:       "",
	}, {
		NameTH:        "บ้านปริศนาบ้านดังบริหารเสน่ห์ ",
		DescriptionTH: "เมื่อหนึ่งในนักเรียนบ้านดังบริหารเสน่ห์  ถูกลักพาตัวด้วยราชินีใจร้ายและทุกคนในโรงเรียนถูกสาปให้จำชื่อของเธอไม่ได้ หนทางเดียวที่จะถอนคำสาปและพานักเรียนคนนั้นกลับมาคือ ทุกคนต้องเอ่ยนามของเธอ ในคืนที่แสงเทียนสว่างกว่าแสงจันทร์ มาร่วมถอดรหัสหาชื่อของเธอเพื่อถอนคำสาปกับเราใน dung charm school secret ปริศนาบ้านดังบริหารเสน่ห์",
		NameEN:        "Baan Dung Charm School Secret",
		DescriptionEN: "One of the students of Dung charm school was abducted by a mean queen. Everyone at school was cursed to forget her name. The only way to remove the curse and bring that student back is for everyone to mention her name on a night when the candlelight is brighter than the moonlight. Come to decipher her name to undo the curse with us in Dung charm school secret.",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Dung-Charm-School-Secret.jpeg",
		Size:          constant.M,
		Facebook:      "baandung",
		FacebookUrl:   "https://www.facebook.com/baandung/",
		Instagram:     "baandung.official",
		InstagramUrl:  "https://www.instagram.com/baandung.official/",
		Line:          "",
		LineUrl:       "",
	},
	{
		NameTH:        "บ้านยิ้ม",
		DescriptionTH: "ถึงเวลาแล้วที่น้องๆ cu106 จะเข้ามาเป็นส่วนหนึ่งในการไขปริศนานี้กัน อย่าลืมเลือก \"บ้านยิ้ม\" ไว้เป็นอันดับ1 ในการเลือกบ้านที่กำลังจะเกิดขึ้นนะ",
		NameEN:        "Baan Yim",
		DescriptionEN: "The investigation is beginning soon Come and be a part of us to experience and solve the mysterious case together Join before it’s too late, Baan Yim",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Yim.jpg",
		Size:          constant.XXL,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanyimchula",
		InstagramUrl:  "https://www.instagram.com/baanyimchula/",
		Line:          "",
		LineUrl:       "",
	},
	{
		NameTH:        "บ้านแรง",
		DescriptionTH: "LA LA RANG \nค่ำคืนนี้ถึงเวลาที่ดวงดาวจะส่องสว่างไปที่น้องเฟรชชี่ \nโบกสะบัดบัตรเชิญให้น้อง ๆ มารวมเฉลิมฉลองเต้นรำจังหวะ jazz ไปด้วยกันกับบ้านแรง มาสนุกกันเถอะ ❤️\nไม่ว่าน้องจะมาจากไหน บ้านหลังนี้พร้อมต้อนรับเสมอ อยากเจอนะอยากเจอ :-)\n\nFacebook : BaanRang CHULA\nInstagram : baanrang.official",
		NameEN:        "Baan Rang",
		DescriptionEN: "LA LA RANG\nCity of stars are you shining just for me? Welcome Freshman... You all are invited to join the amazing jazz party with BaanRang. Let’s have fun together ❤️. I don’t know what you came to do, but I wanna do it with you :-)\n\nFacebook : BaanRang CHULA\nInstagram : baanrang.official",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Rang.jpg",
		Size:          constant.XXL,
		Facebook:      "BaanRang CHULA",
		FacebookUrl:   "https://www.facebook.com/baanrang.official",
		Instagram:     "baanrang.official",
		InstagramUrl:  "https://instagram.com/baanrang.official",
		Line:          "",
		LineUrl:       "",
	},
	{
		NameTH:        "บ้านเพียว",
		DescriptionTH: "ไม่ไหวอย่าฝืน ไม่มีที่ยืนก็มายืนที่บ้านเพียวสิครับ",
		NameEN:        "Baan Pure",
		DescriptionEN: "ไม่ไหวอย่าฝืน ไม่มีที่ยืนก็มายืนที่บ้านเพียวสิครับ",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Pure.JPG",
		Size:          constant.L,
		Facebook:      "",
		FacebookUrl:   "",
		Instagram:     "baanpure.official",
		InstagramUrl:  "https://www.instagram.com/baanpure.official/",
		Line:          "",
		LineUrl:       "",
	},
	{
		NameTH:        "บ้านโคะ",
		DescriptionTH: "บ้านโคะ\n\nบ้านโคะเป็นบ้านแห่งความหลากหลายทางความคิดสร้างสรรค์และความสนุกสนาน ชีวิตมหาลัยปีนี้จะไม่น่าเบื่ออีกต่อไป เมื่ออยู่กับเรา เปลี่ยนเรื่องธรรมดาให้กลายเป็นความทรงจำที่พิเศษในรั้วมหาลัย แต่เปลี่ยนยังไงเธอก็ชอบบ้านเรา (คิมิโนะโต๊ะ) เชิงบังคับดั้ว\n\nแล้วมาสุดมันส์ไปด้วยกันนน\nKoh\nLive like we’re drunk",
		NameEN:        "Baan Koh",
		DescriptionEN: "Baan Koh (Koh House) \nBaan koh (n.) a gathering place of diversity where there’s joy, laughter and smile. Our mission is to treat everyone the best we can regardless of who your are and where you came from. We will change your normal daily life into a wonderful and memorable one.\n\nJoin and “live like you are drunk with us”",
		ImageUrl:      "https://storage.googleapis.com/rnkm-public/Baan-Koh.jpeg",
		Size:          constant.L,
		Facebook:      "BaanKoh",
		FacebookUrl:   "https://www.facebook.com/BaanKoh",
		Instagram:     "baankohchula",
		InstagramUrl:  "https://instagram.com/baankohchula",
		Line:          "",
		LineUrl:       "",
	},
}
